// <auto-generated />
using System;
using CPK5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CPK5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010213535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPK5.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_CP5_PACIENTE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "123456789",
                            DtNascimento = new DateTime(2024, 10, 10, 18, 35, 35, 145, DateTimeKind.Local).AddTicks(7014),
                            Endereco = "endereço inicial",
                            Nome = "Paciente Inicial",
                            Telefone = "123456789"
                        });
                });

            modelBuilder.Entity("CPK5.Models.PacientePlanoSaude", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlanoSaudeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PacienteId", "PlanoSaudeId");

                    b.HasIndex("PlanoSaudeId");

                    b.ToTable("TB_CP5_PACIENTE_PLANO");

                    b.HasData(
                        new
                        {
                            PacienteId = 1,
                            PlanoSaudeId = 1
                        });
                });

            modelBuilder.Entity("CPK5.Models.PlanoSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmPlano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_CP5_PLANO_SAUDE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cobertura = "Cobertura Inicial",
                            NmPlano = "Plano Inicial"
                        });
                });

            modelBuilder.Entity("CPK5.Models.PacientePlanoSaude", b =>
                {
                    b.HasOne("CPK5.Models.Paciente", "Paciente")
                        .WithMany("PacientePlanosSaude")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPK5.Models.PlanoSaude", "PlanoSaude")
                        .WithMany("PacientePlanosSaude")
                        .HasForeignKey("PlanoSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("PlanoSaude");
                });

            modelBuilder.Entity("CPK5.Models.Paciente", b =>
                {
                    b.Navigation("PacientePlanosSaude");
                });

            modelBuilder.Entity("CPK5.Models.PlanoSaude", b =>
                {
                    b.Navigation("PacientePlanosSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
